// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.2-0.20250611151832-b8ebad4d568a DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	TokenScopes = "Token.Scopes"
)

// Article defines model for Article.
type Article struct {
	Author         Profile   `json:"author"`
	Body           string    `json:"body"`
	CreatedAt      time.Time `json:"createdAt"`
	Description    string    `json:"description"`
	Favorited      bool      `json:"favorited"`
	FavoritesCount int       `json:"favoritesCount"`
	Slug           string    `json:"slug"`
	TagList        []string  `json:"tagList"`
	Title          string    `json:"title"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

// Comment defines model for Comment.
type Comment struct {
	Author    Profile   `json:"author"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// GenericErrorModel defines model for GenericErrorModel.
type GenericErrorModel struct {
	Errors struct {
		Body []string `json:"body"`
	} `json:"errors"`
}

// LoginUser defines model for LoginUser.
type LoginUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// NewArticle defines model for NewArticle.
type NewArticle struct {
	Body        string    `json:"body"`
	Description string    `json:"description"`
	TagList     *[]string `json:"tagList,omitempty"`
	Title       string    `json:"title"`
}

// NewComment defines model for NewComment.
type NewComment struct {
	Body string `json:"body"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// Profile defines model for Profile.
type Profile struct {
	Bio       string `json:"bio"`
	Following bool   `json:"following"`
	Image     string `json:"image"`
	Username  string `json:"username"`
}

// UpdateArticle defines model for UpdateArticle.
type UpdateArticle struct {
	Body        *string `json:"body,omitempty"`
	Description *string `json:"description,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// UpdateUser defines model for UpdateUser.
type UpdateUser struct {
	Bio      *string `json:"bio,omitempty"`
	Email    *string `json:"email,omitempty"`
	Image    *string `json:"image,omitempty"`
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// User defines model for User.
type User struct {
	Bio      string `json:"bio"`
	Email    string `json:"email"`
	Image    string `json:"image"`
	Token    string `json:"token"`
	Username string `json:"username"`
}

// LimitParam defines model for limitParam.
type LimitParam = int

// OffsetParam defines model for offsetParam.
type OffsetParam = int

// GenericError defines model for GenericError.
type GenericError = GenericErrorModel

// MultipleArticlesResponse defines model for MultipleArticlesResponse.
type MultipleArticlesResponse struct {
	Articles []struct {
		Author         Profile   `json:"author"`
		CreatedAt      time.Time `json:"createdAt"`
		Description    string    `json:"description"`
		Favorited      bool      `json:"favorited"`
		FavoritesCount int       `json:"favoritesCount"`
		Slug           string    `json:"slug"`
		TagList        []string  `json:"tagList"`
		Title          string    `json:"title"`
		UpdatedAt      time.Time `json:"updatedAt"`
	} `json:"articles"`
	ArticlesCount int `json:"articlesCount"`
}

// MultipleCommentsResponse defines model for MultipleCommentsResponse.
type MultipleCommentsResponse struct {
	Comments []Comment `json:"comments"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	Profile Profile `json:"profile"`
}

// SingleArticleResponse defines model for SingleArticleResponse.
type SingleArticleResponse struct {
	Article Article `json:"article"`
}

// SingleCommentResponse defines model for SingleCommentResponse.
type SingleCommentResponse struct {
	Comment Comment `json:"comment"`
}

// TagsResponse defines model for TagsResponse.
type TagsResponse struct {
	Tags []string `json:"tags"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	User User `json:"user"`
}

// LoginUserRequest defines model for LoginUserRequest.
type LoginUserRequest struct {
	User LoginUser `json:"user"`
}

// NewArticleRequest defines model for NewArticleRequest.
type NewArticleRequest struct {
	Article NewArticle `json:"article"`
}

// NewCommentRequest defines model for NewCommentRequest.
type NewCommentRequest struct {
	Comment NewComment `json:"comment"`
}

// NewUserRequest defines model for NewUserRequest.
type NewUserRequest struct {
	User NewUser `json:"user"`
}

// UpdateArticleRequest defines model for UpdateArticleRequest.
type UpdateArticleRequest struct {
	Article UpdateArticle `json:"article"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	User UpdateUser `json:"user"`
}

// GetArticlesParams defines parameters for GetArticles.
type GetArticlesParams struct {
	// Tag Filter by tag
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// Author Filter by author (username)
	Author *string `form:"author,omitempty" json:"author,omitempty"`

	// Favorited Filter by favorites of a user (username)
	Favorited *string `form:"favorited,omitempty" json:"favorited,omitempty"`

	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateArticleJSONBody defines parameters for CreateArticle.
type CreateArticleJSONBody struct {
	Article NewArticle `json:"article"`
}

// GetArticlesFeedParams defines parameters for GetArticlesFeed.
type GetArticlesFeedParams struct {
	// Offset The number of items to skip before starting to collect the result set.
	Offset *OffsetParam `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit The numbers of items to return.
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
}

// UpdateArticleJSONBody defines parameters for UpdateArticle.
type UpdateArticleJSONBody struct {
	Article UpdateArticle `json:"article"`
}

// CreateArticleCommentJSONBody defines parameters for CreateArticleComment.
type CreateArticleCommentJSONBody struct {
	Comment NewComment `json:"comment"`
}

// UpdateCurrentUserJSONBody defines parameters for UpdateCurrentUser.
type UpdateCurrentUserJSONBody struct {
	User UpdateUser `json:"user"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody struct {
	User NewUser `json:"user"`
}

// LoginJSONBody defines parameters for Login.
type LoginJSONBody struct {
	User LoginUser `json:"user"`
}

// CreateArticleJSONRequestBody defines body for CreateArticle for application/json ContentType.
type CreateArticleJSONRequestBody CreateArticleJSONBody

// UpdateArticleJSONRequestBody defines body for UpdateArticle for application/json ContentType.
type UpdateArticleJSONRequestBody UpdateArticleJSONBody

// CreateArticleCommentJSONRequestBody defines body for CreateArticleComment for application/json ContentType.
type CreateArticleCommentJSONRequestBody CreateArticleCommentJSONBody

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody UpdateCurrentUserJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get recent articles globally
	// (GET /articles)
	GetArticles(w http.ResponseWriter, r *http.Request, params GetArticlesParams)
	// Create an article
	// (POST /articles)
	CreateArticle(w http.ResponseWriter, r *http.Request)
	// Get recent articles from users you follow
	// (GET /articles/feed)
	GetArticlesFeed(w http.ResponseWriter, r *http.Request, params GetArticlesFeedParams)
	// Delete an article
	// (DELETE /articles/{slug})
	DeleteArticle(w http.ResponseWriter, r *http.Request, slug string)
	// Get an article
	// (GET /articles/{slug})
	GetArticle(w http.ResponseWriter, r *http.Request, slug string)
	// Update an article
	// (PUT /articles/{slug})
	UpdateArticle(w http.ResponseWriter, r *http.Request, slug string)
	// Get comments for an article
	// (GET /articles/{slug}/comments)
	GetArticleComments(w http.ResponseWriter, r *http.Request, slug string)
	// Create a comment for an article
	// (POST /articles/{slug}/comments)
	CreateArticleComment(w http.ResponseWriter, r *http.Request, slug string)
	// Delete a comment for an article
	// (DELETE /articles/{slug}/comments/{id})
	DeleteArticleComment(w http.ResponseWriter, r *http.Request, slug string, id int)
	// Unfavorite an article
	// (DELETE /articles/{slug}/favorite)
	DeleteArticleFavorite(w http.ResponseWriter, r *http.Request, slug string)
	// Favorite an article
	// (POST /articles/{slug}/favorite)
	CreateArticleFavorite(w http.ResponseWriter, r *http.Request, slug string)
	// Get a profile
	// (GET /profiles/{username})
	GetProfileByUsername(w http.ResponseWriter, r *http.Request, username string)
	// Unfollow a user
	// (DELETE /profiles/{username}/follow)
	UnfollowUserByUsername(w http.ResponseWriter, r *http.Request, username string)
	// Follow a user
	// (POST /profiles/{username}/follow)
	FollowUserByUsername(w http.ResponseWriter, r *http.Request, username string)
	// Get tags
	// (GET /tags)
	GetTags(w http.ResponseWriter, r *http.Request)
	// Get current user
	// (GET /user)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Update current user
	// (PUT /user)
	UpdateCurrentUser(w http.ResponseWriter, r *http.Request)

	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Existing user login
	// (POST /users/login)
	Login(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get recent articles globally
// (GET /articles)
func (_ Unimplemented) GetArticles(w http.ResponseWriter, r *http.Request, params GetArticlesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an article
// (POST /articles)
func (_ Unimplemented) CreateArticle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get recent articles from users you follow
// (GET /articles/feed)
func (_ Unimplemented) GetArticlesFeed(w http.ResponseWriter, r *http.Request, params GetArticlesFeedParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an article
// (DELETE /articles/{slug})
func (_ Unimplemented) DeleteArticle(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an article
// (GET /articles/{slug})
func (_ Unimplemented) GetArticle(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an article
// (PUT /articles/{slug})
func (_ Unimplemented) UpdateArticle(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get comments for an article
// (GET /articles/{slug}/comments)
func (_ Unimplemented) GetArticleComments(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a comment for an article
// (POST /articles/{slug}/comments)
func (_ Unimplemented) CreateArticleComment(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a comment for an article
// (DELETE /articles/{slug}/comments/{id})
func (_ Unimplemented) DeleteArticleComment(w http.ResponseWriter, r *http.Request, slug string, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unfavorite an article
// (DELETE /articles/{slug}/favorite)
func (_ Unimplemented) DeleteArticleFavorite(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Favorite an article
// (POST /articles/{slug}/favorite)
func (_ Unimplemented) CreateArticleFavorite(w http.ResponseWriter, r *http.Request, slug string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a profile
// (GET /profiles/{username})
func (_ Unimplemented) GetProfileByUsername(w http.ResponseWriter, r *http.Request, username string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unfollow a user
// (DELETE /profiles/{username}/follow)
func (_ Unimplemented) UnfollowUserByUsername(w http.ResponseWriter, r *http.Request, username string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Follow a user
// (POST /profiles/{username}/follow)
func (_ Unimplemented) FollowUserByUsername(w http.ResponseWriter, r *http.Request, username string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get tags
// (GET /tags)
func (_ Unimplemented) GetTags(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user
// (GET /user)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update current user
// (PUT /user)
func (_ Unimplemented) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Existing user login
// (POST /users/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetArticles operation middleware
func (siw *ServerInterfaceWrapper) GetArticles(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArticlesParams

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", r.URL.Query(), &params.Tag)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	// ------------- Optional query parameter "author" -------------

	err = runtime.BindQueryParameter("form", true, false, "author", r.URL.Query(), &params.Author)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author", Err: err})
		return
	}

	// ------------- Optional query parameter "favorited" -------------

	err = runtime.BindQueryParameter("form", true, false, "favorited", r.URL.Query(), &params.Favorited)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "favorited", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateArticle operation middleware
func (siw *ServerInterfaceWrapper) CreateArticle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateArticle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticlesFeed operation middleware
func (siw *ServerInterfaceWrapper) GetArticlesFeed(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArticlesFeedParams

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticlesFeed(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArticle operation middleware
func (siw *ServerInterfaceWrapper) DeleteArticle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArticle(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticle operation middleware
func (siw *ServerInterfaceWrapper) GetArticle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticle(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateArticle operation middleware
func (siw *ServerInterfaceWrapper) UpdateArticle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateArticle(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticleComments operation middleware
func (siw *ServerInterfaceWrapper) GetArticleComments(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticleComments(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateArticleComment operation middleware
func (siw *ServerInterfaceWrapper) CreateArticleComment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateArticleComment(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArticleComment operation middleware
func (siw *ServerInterfaceWrapper) DeleteArticleComment(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArticleComment(w, r, slug, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArticleFavorite operation middleware
func (siw *ServerInterfaceWrapper) DeleteArticleFavorite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArticleFavorite(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateArticleFavorite operation middleware
func (siw *ServerInterfaceWrapper) CreateArticleFavorite(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", chi.URLParam(r, "slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateArticleFavorite(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfileByUsername operation middleware
func (siw *ServerInterfaceWrapper) GetProfileByUsername(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfileByUsername(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnfollowUserByUsername operation middleware
func (siw *ServerInterfaceWrapper) UnfollowUserByUsername(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnfollowUserByUsername(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FollowUserByUsername operation middleware
func (siw *ServerInterfaceWrapper) FollowUserByUsername(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "username" -------------
	var username string

	err = runtime.BindStyledParameterWithOptions("simple", "username", chi.URLParam(r, "username"), &username, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "username", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FollowUserByUsername(w, r, username)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTags operation middleware
func (siw *ServerInterfaceWrapper) GetTags(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTags(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, TokenScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles", wrapper.GetArticles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/articles", wrapper.CreateArticle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles/feed", wrapper.GetArticlesFeed)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/articles/{slug}", wrapper.DeleteArticle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles/{slug}", wrapper.GetArticle)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/articles/{slug}", wrapper.UpdateArticle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles/{slug}/comments", wrapper.GetArticleComments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/articles/{slug}/comments", wrapper.CreateArticleComment)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/articles/{slug}/comments/{id}", wrapper.DeleteArticleComment)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/articles/{slug}/favorite", wrapper.DeleteArticleFavorite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/articles/{slug}/favorite", wrapper.CreateArticleFavorite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/profiles/{username}", wrapper.GetProfileByUsername)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/profiles/{username}/follow", wrapper.UnfollowUserByUsername)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/profiles/{username}/follow", wrapper.FollowUserByUsername)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags", wrapper.GetTags)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/user", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/user", wrapper.UpdateCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/login", wrapper.Login)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbW3PbNvb/Khj8/zPdzciik+1DR2+uE3eym3QziT19SPIAkUcUGhBgAdCO6tF338GN",
	"hHiRKJlJvN3kJRYJHJzL71xwAN7jVBSl4MC1wot7XBJJCtAg7S9GC6rfmEfmVwYqlbTUVHC8wNdrQLwq",
	"liAVEitENRQKaYEk6EryOZ5haob9UYHc4BnmpAC8cBTxDKt0DQVxVFekYhovnp3PcEE5LaoCL57OsN6U",
	"ZgblGnKQeLudYbFaKTjM0A4/6hMt0RJWQgJSmkhNeW6ep4IxSDXSa0ASVMU0UqCH+HYr7zBe83rew+t2",
	"hiX8UYHSP4uMgtXmK5FTfqNAvnVvzLNUcA3c/knKktGUGGmS35UR6T5arZSiBKk9qUqBNP//v4QVXuD/",
	"SxorJm6OSurlcOCGSsjw4r2b/bHmWix/h1Q7pndVeikhA64pYVaVlQIcU9Kygu0M/wp3F1LTlMHDBSOO",
	"0CHZmiU7wgUKY+TzNCwcJBA9JN6lKArg+uHipY7QCPH8kh3xAoVR5nNj0UZU6I5wfVDOrwdOv9jp0HwO",
	"mlBmQ4/xYA53Bp7SRaCcKg2yT8ibMiMavjZcd1adCrGVJTos5NczZrPe6fY0s1HmjVpLN0cXGjEgSqMn",
	"TwSHJ0/QigLLEFUoLDPvqsAyoUrBlRPiRVHqzb8/vfXPurnjV5MPnH62M/wLcJA0fSGlkEepbp+SYqKv",
	"RQasVwscPpeQasgQ2NW3M/y6YpqWLMBHxVI8DLb2b5soe4ZUei0OWv6NFCtqID3DLrBkF5aZlZAF0XiB",
	"jRHPNC0MTj0GlJaU57gt+333/YrcCkm1MWv9dikEA8Lj1+pSVE4H7TQ8w4pVeS9tTfJX1HlGrYHuIPeA",
	"SEk29jfVztk7Ix1cj5C+HQOcumM17uon1kZHdC9nI1VgNWas64VdAQMwBjXaH7oUbk8d4/IB2KimEqHd",
	"564p0O5T5i7a96G6zr1tBfXnYnWctPWs7Qx7/5lAyNJ74liHbYkSpo+RJHL6d5TnrEmnUwWmQ1JMkUkd",
	"6wF7jTB1rTcV7kaj7QGVnhcmbYB7TfIpfEeTXB0TI1sy2OljBDDsGmo33EVC+qeL+u30GL01o22J82Ah",
	"R9U4D65u7GxPzqx20WD9gal3KbJNr22+5+RJcrLV79dOzZdN9HhE8KBZv02/pK5pdlBZ3eK6ozZbT/cU",
	"ukE7J0Y4O70nBOyO8ov3sd60abosF4SyXpZKotSdkNmOtuuHh5Tt6EZU+viKWiyDOjs6ekzq4X2WaHum",
	"mzsg36CLDcg3zvR1J+ULGnRmU4/rTd4fa+1och/3b5pKsqUVKvpTgmBM3JkfvSmBFiQfCNCjZTBLxwsF",
	"qgdE2e27TAjjYUQO8NCPhyGNDuNkWJkxgo7UdJfnL86tFp+ATwKKAO8ACEd5LzBMDQJpJanevDPp0ol3",
	"HVjaLd2uhEQkTUEpe3CwBlRKoV2P5uLNSyRBiUqmoGa2z1pUSqM1uQUkIQV6CxkiiKBbwmiG/vnbNbL8",
	"IbLSIOtOpaEsJGIiz82flM/R9ZqqaLwlq9fA0RJQpSBDK8MXYxE3NSdouUEGDpaWRpSjW0os6z9c+PrZ",
	"FsY/oDWQDOT8A//AL6LVqEK5yagm4xpiZqqRdblBQPW6xbkhnhh1q10hohcJM1nOrnO9BlQ7MnKxzom3",
	"BDNpmE20MPMRQsiaCn22/+Yb92/+p/3nBnzg4RzHTW0OcnYoN4GVlPRfsHGlO+UrEXYTJLXpwU9+C4T9",
	"JiSzMVQyQ17rUi2SRAJhd+bNWSZSNeegGV1t5qQsE9zTl+dZRbVVaSbSyiShwA+jKfjdjF/09ctr9Mo/",
	"bS8rSuDO6HMh88RPVsnrl9dRnGr4RtHSeIZvQSrH0tP5+fzcTDEUSUnxAv9jfj5/avOGXlsHSeK2YQ66",
	"6yu/gEaFUNpin+u6sYNyJpaEsc0c3ShA9mwNNUeNSAu0osx5hKqYVnNk7GRwKCxtYjzcxCKrppeZW+ui",
	"6T7F55bvOy7saBsgk3zggM+9aXaIndAzTNTVruhvIeL8fWCJusY9aZV6X4HEChF32HFwyXhjsnfVvq1E",
	"o9MkPngdMTw6N95+bPXin52fD+1d6nHJYM97O8M/nj89TKDdKfjx2bPDk3b6/jZLVEVB5MYjewjUbnNn",
	"gIdrRH40GVmoHh+5tDsbRHgg1GC9Tm5trLs5oY6Jj5Y3w1JFp89J94h22zHLCK32t/u+sk185rZ+7nP2",
	"+48GZo21OjruNdEMfz5LRQY58DOvrjNTEp4Ff426jHXsS1bgeh/HBcCVFAVyOdJUCS4BDkdD60AjgBEF",
	"wSuw71uB8Ltfn4qhPo/vtWK/++9g5l6xKt86uDDQPQeQz+3z46KCm9NEhb058B2r8nBYTppDZM+Pzx4m",
	"1TfJwzeuds9W9+WRkyDRPpt9fEjo2GYo4A+GhI5ZudBjnPpEo+b2ptI3s+hwlpggCR+2Qln1WMHtwo/z",
	"r93uwWmmqC9pTGaNIzN/74WX7bRmfVzu2jH1hMnfBfIkPlEedHqDhDDQ7dZ7wDdiexNOwk9C4JrsXv/K",
	"Qe8w9S3jxOBR/7cs8gcsFmGotsfhGj9QGzT/uIo/9KmnAEDaw9o3DE/dy5UPiE3to/vHuzEZAEYvyg5F",
	"qjS6PzAYqZJ7mo0qQE+H7E45OiVksx7WJoJsp9/y8nlgJ+25PLuvWranlAdXbi5S/cWL5WMQ3ovc0Lra",
	"B9obHkY9AKpXYaEpsFrVHD3OCvyRlWp99osgEkyzL9denYSAnfw6KQK+23+8/a9GW99ECH9HUSX3oe29",
	"3VuAE+RnRB1zbz21URqKcWW4Pw//eXMTThQPwCSMC4sFLvbtzKuG9hfGRvvK6bcstmsLRVYP1w8GbZ74",
	"ttv+vGDHBKsvNyhScGuX78caqz3cxq1cEBqE/8sWH5cHYnv1omEw/o+29NUXsvN3K4+M9gdtbDw+3Dge",
	"7quQXI1so9pbxacoc+f29ETBTjtmgtSWNydyuH88JLJyG5JKSuCabewVC8jOKA+a7Ah+6cbeKP8V3LHy",
	"71ysfpxnM14dbTDZ78gIzyxAgGt/B/xQZzhz4YNydyGFCm43Lq1F+vrDbVWf1J+Nv9Xb/gUN5nuyx9rs",
	"UOvDXuCrXchd7u1NEm/9dSVE6i9FB7YEp9qx9fXsScfrHSOeZI+pterubg3r1l5gtt4Cn6myn9f36teO",
	"O0W1ne/m/+s8pPaDF7GGEPMamcpi1hnlbahkmqtiiyRhIiVsLZRe/HT+03lCSmqP8P3S9WWzi+ZTvPrZ",
	"ZfPBWv2s2ZtFD5tvDupH/rue+veQiNuP2/8EAAD//xbPXD+LQgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
